/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConstructionStep {
  'durationDays' : bigint,
  'step' : bigint,
  'activities' : [] | [string],
  'description' : string,
  'stageImageUrl' : [] | [string],
  'stageName' : [] | [string],
  'stageType' : [] | [string],
}
export interface CostBreakdown {
  'roofing' : bigint,
  'foundation' : bigint,
  'structure' : bigint,
  'plumbing' : bigint,
  'electrical' : bigint,
  'finishing' : bigint,
  'flooring' : bigint,
}
export interface CostCalculatorInput {
  'region' : Region,
  'materialGrade' : MaterialGrade,
  'areaSqft' : bigint,
}
export interface CostCalculatorResult {
  'costPerSqft' : bigint,
  'breakdown' : CostBreakdown,
  'totalCost' : bigint,
}
export interface Design {
  'id' : bigint,
  'bhk' : [] | [bigint],
  'floorPlanImageUrl' : string,
  'title' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'tier' : DesignTier,
  'description' : string,
  'materials' : Array<Material>,
  'estimatedCostMax' : bigint,
  'estimatedCostMin' : bigint,
  'areaSqft' : bigint,
  'category' : DesignCategory,
  'constructionSteps' : Array<ConstructionStep>,
  'previewImageUrl' : string,
}
export type DesignCategory = { 'custom' : null } |
  { 'residential' : null } |
  { 'apartments' : null } |
  { 'smallBusiness' : null } |
  { 'dairyFarms' : null };
export interface DesignFilter {
  'tier' : [] | [DesignTier],
  'category' : [] | [DesignCategory],
}
export interface DesignSummary {
  'id' : bigint,
  'bhk' : [] | [bigint],
  'title' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'tier' : DesignTier,
  'estimatedCostMax' : bigint,
  'estimatedCostMin' : bigint,
  'areaSqft' : bigint,
  'category' : DesignCategory,
  'previewImageUrl' : string,
}
export type DesignTier = { 'ultraPremium' : null } |
  { 'premium' : null } |
  { 'free' : null };
export interface InquiryPublic {
  'id' : bigint,
  'status' : InquiryStatus,
  'projectType' : string,
  'submitterPrincipal' : [] | [Principal],
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'email' : string,
  'phone' : string,
  'budgetMax' : bigint,
  'budgetMin' : bigint,
}
export type InquiryStatus = { 'responded' : null } |
  { 'pending' : null } |
  { 'reviewed' : null };
export interface Material {
  'costPerUnit' : bigint,
  'name' : string,
  'unit' : string,
  'quantity' : number,
}
export type MaterialGrade = { 'premium' : null } |
  { 'basic' : null } |
  { 'standard' : null };
export type Region = { 'semiUrban' : null } |
  { 'urban' : null } |
  { 'rural' : null };
export interface SubmitInquiryInput {
  'projectType' : string,
  'name' : string,
  'description' : string,
  'email' : string,
  'phone' : string,
  'budgetMax' : bigint,
  'budgetMin' : bigint,
}
export type Timestamp = bigint;
export interface UpdateProfileInput { 'displayName' : string, 'email' : string }
export interface UserProfilePublic {
  'principal' : Principal,
  'displayName' : string,
  'createdAt' : Timestamp,
  'tier' : UserTier,
  'email' : string,
  'savedDesignIds' : Array<bigint>,
}
export type UserTier = { 'ultraPremium' : null } |
  { 'premium' : null } |
  { 'free' : null };
export interface _SERVICE {
  'adminListAllInquiries' : ActorMethod<[], Array<InquiryPublic>>,
  'adminSetUserTier' : ActorMethod<
    [Principal, UserTier],
    { 'ok' : null } |
      { 'notAuthorized' : null } |
      { 'notFound' : null }
  >,
  'adminUpdateInquiryStatus' : ActorMethod<
    [bigint, InquiryStatus],
    { 'ok' : null } |
      { 'notAuthorized' : null } |
      { 'notFound' : null }
  >,
  'calculateCost' : ActorMethod<[CostCalculatorInput], CostCalculatorResult>,
  'getDesign' : ActorMethod<[bigint], [] | [Design]>,
  'getMyInquiries' : ActorMethod<[], Array<InquiryPublic>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getSavedDesigns' : ActorMethod<[], Array<Design>>,
  'listDesigns' : ActorMethod<[DesignFilter], Array<DesignSummary>>,
  'removeSavedDesign' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'notAuthenticated' : null } |
      { 'notFound' : null }
  >,
  'saveDesign' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'notAuthenticated' : null } |
      { 'notFound' : null } |
      { 'limitReached' : null }
  >,
  'submitInquiry' : ActorMethod<[SubmitInquiryInput], InquiryPublic>,
  'updateMyProfile' : ActorMethod<
    [UpdateProfileInput],
    { 'ok' : UserProfilePublic } |
      { 'notAuthenticated' : null }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];