/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InquiryStatus = IDL.Variant({
  'responded' : IDL.Null,
  'pending' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const InquiryPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : InquiryStatus,
  'projectType' : IDL.Text,
  'submitterPrincipal' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'budgetMax' : IDL.Nat,
  'budgetMin' : IDL.Nat,
});
export const UserTier = IDL.Variant({
  'ultraPremium' : IDL.Null,
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const Region = IDL.Variant({
  'semiUrban' : IDL.Null,
  'urban' : IDL.Null,
  'rural' : IDL.Null,
});
export const MaterialGrade = IDL.Variant({
  'premium' : IDL.Null,
  'basic' : IDL.Null,
  'standard' : IDL.Null,
});
export const CostCalculatorInput = IDL.Record({
  'region' : Region,
  'materialGrade' : MaterialGrade,
  'areaSqft' : IDL.Nat,
});
export const CostBreakdown = IDL.Record({
  'roofing' : IDL.Nat,
  'foundation' : IDL.Nat,
  'structure' : IDL.Nat,
  'plumbing' : IDL.Nat,
  'electrical' : IDL.Nat,
  'finishing' : IDL.Nat,
  'flooring' : IDL.Nat,
});
export const CostCalculatorResult = IDL.Record({
  'costPerSqft' : IDL.Nat,
  'breakdown' : CostBreakdown,
  'totalCost' : IDL.Nat,
});
export const DesignTier = IDL.Variant({
  'ultraPremium' : IDL.Null,
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const Material = IDL.Record({
  'costPerUnit' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Float64,
});
export const DesignCategory = IDL.Variant({
  'custom' : IDL.Null,
  'residential' : IDL.Null,
  'apartments' : IDL.Null,
  'smallBusiness' : IDL.Null,
  'dairyFarms' : IDL.Null,
});
export const ConstructionStep = IDL.Record({
  'durationDays' : IDL.Nat,
  'step' : IDL.Nat,
  'activities' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'stageImageUrl' : IDL.Opt(IDL.Text),
  'stageName' : IDL.Opt(IDL.Text),
  'stageType' : IDL.Opt(IDL.Text),
});
export const Design = IDL.Record({
  'id' : IDL.Nat,
  'bhk' : IDL.Opt(IDL.Nat),
  'floorPlanImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'tier' : DesignTier,
  'description' : IDL.Text,
  'materials' : IDL.Vec(Material),
  'estimatedCostMax' : IDL.Nat,
  'estimatedCostMin' : IDL.Nat,
  'areaSqft' : IDL.Nat,
  'category' : DesignCategory,
  'constructionSteps' : IDL.Vec(ConstructionStep),
  'previewImageUrl' : IDL.Text,
});
export const UserProfilePublic = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'tier' : UserTier,
  'email' : IDL.Text,
  'savedDesignIds' : IDL.Vec(IDL.Nat),
});
export const DesignFilter = IDL.Record({
  'tier' : IDL.Opt(DesignTier),
  'category' : IDL.Opt(DesignCategory),
});
export const DesignSummary = IDL.Record({
  'id' : IDL.Nat,
  'bhk' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'tier' : DesignTier,
  'estimatedCostMax' : IDL.Nat,
  'estimatedCostMin' : IDL.Nat,
  'areaSqft' : IDL.Nat,
  'category' : DesignCategory,
  'previewImageUrl' : IDL.Text,
});
export const SubmitInquiryInput = IDL.Record({
  'projectType' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'budgetMax' : IDL.Nat,
  'budgetMin' : IDL.Nat,
});
export const UpdateProfileInput = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminListAllInquiries' : IDL.Func([], [IDL.Vec(InquiryPublic)], ['query']),
  'adminSetUserTier' : IDL.Func(
      [IDL.Principal, UserTier],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'notAuthorized' : IDL.Null,
          'notFound' : IDL.Null,
        }),
      ],
      [],
    ),
  'adminUpdateInquiryStatus' : IDL.Func(
      [IDL.Nat, InquiryStatus],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'notAuthorized' : IDL.Null,
          'notFound' : IDL.Null,
        }),
      ],
      [],
    ),
  'calculateCost' : IDL.Func(
      [CostCalculatorInput],
      [CostCalculatorResult],
      ['query'],
    ),
  'getDesign' : IDL.Func([IDL.Nat], [IDL.Opt(Design)], ['query']),
  'getMyInquiries' : IDL.Func([], [IDL.Vec(InquiryPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getSavedDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'listDesigns' : IDL.Func([DesignFilter], [IDL.Vec(DesignSummary)], ['query']),
  'removeSavedDesign' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'notAuthenticated' : IDL.Null,
          'notFound' : IDL.Null,
        }),
      ],
      [],
    ),
  'saveDesign' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'notAuthenticated' : IDL.Null,
          'notFound' : IDL.Null,
          'limitReached' : IDL.Null,
        }),
      ],
      [],
    ),
  'submitInquiry' : IDL.Func([SubmitInquiryInput], [InquiryPublic], []),
  'updateMyProfile' : IDL.Func(
      [UpdateProfileInput],
      [
        IDL.Variant({
          'ok' : UserProfilePublic,
          'notAuthenticated' : IDL.Null,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InquiryStatus = IDL.Variant({
    'responded' : IDL.Null,
    'pending' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const InquiryPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : InquiryStatus,
    'projectType' : IDL.Text,
    'submitterPrincipal' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'budgetMax' : IDL.Nat,
    'budgetMin' : IDL.Nat,
  });
  const UserTier = IDL.Variant({
    'ultraPremium' : IDL.Null,
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const Region = IDL.Variant({
    'semiUrban' : IDL.Null,
    'urban' : IDL.Null,
    'rural' : IDL.Null,
  });
  const MaterialGrade = IDL.Variant({
    'premium' : IDL.Null,
    'basic' : IDL.Null,
    'standard' : IDL.Null,
  });
  const CostCalculatorInput = IDL.Record({
    'region' : Region,
    'materialGrade' : MaterialGrade,
    'areaSqft' : IDL.Nat,
  });
  const CostBreakdown = IDL.Record({
    'roofing' : IDL.Nat,
    'foundation' : IDL.Nat,
    'structure' : IDL.Nat,
    'plumbing' : IDL.Nat,
    'electrical' : IDL.Nat,
    'finishing' : IDL.Nat,
    'flooring' : IDL.Nat,
  });
  const CostCalculatorResult = IDL.Record({
    'costPerSqft' : IDL.Nat,
    'breakdown' : CostBreakdown,
    'totalCost' : IDL.Nat,
  });
  const DesignTier = IDL.Variant({
    'ultraPremium' : IDL.Null,
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const Material = IDL.Record({
    'costPerUnit' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  const DesignCategory = IDL.Variant({
    'custom' : IDL.Null,
    'residential' : IDL.Null,
    'apartments' : IDL.Null,
    'smallBusiness' : IDL.Null,
    'dairyFarms' : IDL.Null,
  });
  const ConstructionStep = IDL.Record({
    'durationDays' : IDL.Nat,
    'step' : IDL.Nat,
    'activities' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'stageImageUrl' : IDL.Opt(IDL.Text),
    'stageName' : IDL.Opt(IDL.Text),
    'stageType' : IDL.Opt(IDL.Text),
  });
  const Design = IDL.Record({
    'id' : IDL.Nat,
    'bhk' : IDL.Opt(IDL.Nat),
    'floorPlanImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'tier' : DesignTier,
    'description' : IDL.Text,
    'materials' : IDL.Vec(Material),
    'estimatedCostMax' : IDL.Nat,
    'estimatedCostMin' : IDL.Nat,
    'areaSqft' : IDL.Nat,
    'category' : DesignCategory,
    'constructionSteps' : IDL.Vec(ConstructionStep),
    'previewImageUrl' : IDL.Text,
  });
  const UserProfilePublic = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'tier' : UserTier,
    'email' : IDL.Text,
    'savedDesignIds' : IDL.Vec(IDL.Nat),
  });
  const DesignFilter = IDL.Record({
    'tier' : IDL.Opt(DesignTier),
    'category' : IDL.Opt(DesignCategory),
  });
  const DesignSummary = IDL.Record({
    'id' : IDL.Nat,
    'bhk' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'tier' : DesignTier,
    'estimatedCostMax' : IDL.Nat,
    'estimatedCostMin' : IDL.Nat,
    'areaSqft' : IDL.Nat,
    'category' : DesignCategory,
    'previewImageUrl' : IDL.Text,
  });
  const SubmitInquiryInput = IDL.Record({
    'projectType' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'budgetMax' : IDL.Nat,
    'budgetMin' : IDL.Nat,
  });
  const UpdateProfileInput = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'adminListAllInquiries' : IDL.Func([], [IDL.Vec(InquiryPublic)], ['query']),
    'adminSetUserTier' : IDL.Func(
        [IDL.Principal, UserTier],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'notAuthorized' : IDL.Null,
            'notFound' : IDL.Null,
          }),
        ],
        [],
      ),
    'adminUpdateInquiryStatus' : IDL.Func(
        [IDL.Nat, InquiryStatus],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'notAuthorized' : IDL.Null,
            'notFound' : IDL.Null,
          }),
        ],
        [],
      ),
    'calculateCost' : IDL.Func(
        [CostCalculatorInput],
        [CostCalculatorResult],
        ['query'],
      ),
    'getDesign' : IDL.Func([IDL.Nat], [IDL.Opt(Design)], ['query']),
    'getMyInquiries' : IDL.Func([], [IDL.Vec(InquiryPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getSavedDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'listDesigns' : IDL.Func(
        [DesignFilter],
        [IDL.Vec(DesignSummary)],
        ['query'],
      ),
    'removeSavedDesign' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'notAuthenticated' : IDL.Null,
            'notFound' : IDL.Null,
          }),
        ],
        [],
      ),
    'saveDesign' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'notAuthenticated' : IDL.Null,
            'notFound' : IDL.Null,
            'limitReached' : IDL.Null,
          }),
        ],
        [],
      ),
    'submitInquiry' : IDL.Func([SubmitInquiryInput], [InquiryPublic], []),
    'updateMyProfile' : IDL.Func(
        [UpdateProfileInput],
        [
          IDL.Variant({
            'ok' : UserProfilePublic,
            'notAuthenticated' : IDL.Null,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };