/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface DesignFilter {
    tier?: DesignTier;
    category?: DesignCategory;
}
export interface CostCalculatorInput {
    region: Region;
    materialGrade: MaterialGrade;
    areaSqft: bigint;
}
export interface UserProfilePublic {
    principal: Principal;
    displayName: string;
    createdAt: Timestamp;
    tier: UserTier;
    email: string;
    savedDesignIds: Array<bigint>;
}
export interface Material {
    costPerUnit: bigint;
    name: string;
    unit: string;
    quantity: number;
}
export interface Design {
    id: bigint;
    bhk?: bigint;
    floorPlanImageUrl: string;
    title: string;
    createdAt: Timestamp;
    tags: Array<string>;
    tier: DesignTier;
    description: string;
    materials: Array<Material>;
    estimatedCostMax: bigint;
    estimatedCostMin: bigint;
    areaSqft: bigint;
    category: DesignCategory;
    constructionSteps: Array<ConstructionStep>;
    previewImageUrl: string;
}
export interface UpdateProfileInput {
    displayName: string;
    email: string;
}
export interface SubmitInquiryInput {
    projectType: string;
    name: string;
    description: string;
    email: string;
    phone: string;
    budgetMax: bigint;
    budgetMin: bigint;
}
export interface DesignSummary {
    id: bigint;
    bhk?: bigint;
    title: string;
    createdAt: Timestamp;
    tags: Array<string>;
    tier: DesignTier;
    estimatedCostMax: bigint;
    estimatedCostMin: bigint;
    areaSqft: bigint;
    category: DesignCategory;
    previewImageUrl: string;
}
export interface CostCalculatorResult {
    costPerSqft: bigint;
    breakdown: CostBreakdown;
    totalCost: bigint;
}
export interface CostBreakdown {
    roofing: bigint;
    foundation: bigint;
    structure: bigint;
    plumbing: bigint;
    electrical: bigint;
    finishing: bigint;
    flooring: bigint;
}
export interface ConstructionStep {
    durationDays: bigint;
    step: bigint;
    activities?: string;
    description: string;
    stageImageUrl?: string;
    stageName?: string;
    stageType?: string;
}
export interface InquiryPublic {
    id: bigint;
    status: InquiryStatus;
    projectType: string;
    submitterPrincipal?: Principal;
    name: string;
    createdAt: Timestamp;
    description: string;
    email: string;
    phone: string;
    budgetMax: bigint;
    budgetMin: bigint;
}
export enum DesignCategory {
    custom = "custom",
    residential = "residential",
    apartments = "apartments",
    smallBusiness = "smallBusiness",
    dairyFarms = "dairyFarms"
}
export enum DesignTier {
    ultraPremium = "ultraPremium",
    premium = "premium",
    free = "free"
}
export enum InquiryStatus {
    responded = "responded",
    pending = "pending",
    reviewed = "reviewed"
}
export enum MaterialGrade {
    premium = "premium",
    basic = "basic",
    standard = "standard"
}
export enum Region {
    semiUrban = "semiUrban",
    urban = "urban",
    rural = "rural"
}
export enum Variant_ok_notAuthenticated_notFound {
    ok = "ok",
    notAuthenticated = "notAuthenticated",
    notFound = "notFound"
}
export enum Variant_ok_notAuthenticated_notFound_limitReached {
    ok = "ok",
    notAuthenticated = "notAuthenticated",
    notFound = "notFound",
    limitReached = "limitReached"
}
export enum Variant_ok_notAuthorized_notFound {
    ok = "ok",
    notAuthorized = "notAuthorized",
    notFound = "notFound"
}
export interface backendInterface {
    adminListAllInquiries(): Promise<Array<InquiryPublic>>;
    adminSetUserTier(target: Principal, tier: UserTier): Promise<Variant_ok_notAuthorized_notFound>;
    adminUpdateInquiryStatus(id: bigint, status: InquiryStatus): Promise<Variant_ok_notAuthorized_notFound>;
    calculateCost(input: CostCalculatorInput): Promise<CostCalculatorResult>;
    getDesign(id: bigint): Promise<Design | null>;
    getMyInquiries(): Promise<Array<InquiryPublic>>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getSavedDesigns(): Promise<Array<Design>>;
    listDesigns(filter: DesignFilter): Promise<Array<DesignSummary>>;
    removeSavedDesign(designId: bigint): Promise<Variant_ok_notAuthenticated_notFound>;
    saveDesign(designId: bigint): Promise<Variant_ok_notAuthenticated_notFound_limitReached>;
    submitInquiry(input: SubmitInquiryInput): Promise<InquiryPublic>;
    updateMyProfile(input: UpdateProfileInput): Promise<{
        __kind__: "ok";
        ok: UserProfilePublic;
    } | {
        __kind__: "notAuthenticated";
        notAuthenticated: null;
    }>;
}
import type { ConstructionStep as _ConstructionStep, CostCalculatorInput as _CostCalculatorInput, Design as _Design, DesignCategory as _DesignCategory, DesignFilter as _DesignFilter, DesignSummary as _DesignSummary, DesignTier as _DesignTier, InquiryPublic as _InquiryPublic, InquiryStatus as _InquiryStatus, Material as _Material, MaterialGrade as _MaterialGrade, Region as _Region, Timestamp as _Timestamp, UserProfilePublic as _UserProfilePublic, UserTier as _UserTier } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminListAllInquiries(): Promise<Array<InquiryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllInquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllInquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSetUserTier(arg0: Principal, arg1: UserTier): Promise<Variant_ok_notAuthorized_notFound> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetUserTier(arg0, to_candid_UserTier_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetUserTier(arg0, to_candid_UserTier_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateInquiryStatus(arg0: bigint, arg1: InquiryStatus): Promise<Variant_ok_notAuthorized_notFound> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateInquiryStatus(arg0, to_candid_InquiryStatus_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateInquiryStatus(arg0, to_candid_InquiryStatus_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async calculateCost(arg0: CostCalculatorInput): Promise<CostCalculatorResult> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateCost(to_candid_CostCalculatorInput_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateCost(to_candid_CostCalculatorInput_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getDesign(arg0: bigint): Promise<Design | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesign(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesign(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInquiries(): Promise<Array<InquiryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedDesigns(): Promise<Array<Design>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedDesigns();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedDesigns();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDesigns(arg0: DesignFilter): Promise<Array<DesignSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDesigns(to_candid_DesignFilter_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDesigns(to_candid_DesignFilter_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeSavedDesign(arg0: bigint): Promise<Variant_ok_notAuthenticated_notFound> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSavedDesign(arg0);
                return from_candid_variant_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSavedDesign(arg0);
            return from_candid_variant_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDesign(arg0: bigint): Promise<Variant_ok_notAuthenticated_notFound_limitReached> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDesign(arg0);
                return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDesign(arg0);
            return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitInquiry(arg0: SubmitInquiryInput): Promise<InquiryPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0);
                return from_candid_InquiryPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0);
            return from_candid_InquiryPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: UpdateProfileInput): Promise<{
        __kind__: "ok";
        ok: UserProfilePublic;
    } | {
        __kind__: "notAuthenticated";
        notAuthenticated: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0);
                return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0);
            return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ConstructionStep_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConstructionStep): ConstructionStep {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_DesignCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignCategory): DesignCategory {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_DesignSummary_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignSummary): DesignSummary {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_DesignTier_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignTier): DesignTier {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Design_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Design): Design {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryPublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryPublic): InquiryPublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryStatus): InquiryStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserTier_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserTier): UserTier {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Design]): Design | null {
    return value.length === 0 ? null : from_candid_Design_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bhk: [] | [bigint];
    floorPlanImageUrl: string;
    title: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    tier: _DesignTier;
    description: string;
    materials: Array<_Material>;
    estimatedCostMax: bigint;
    estimatedCostMin: bigint;
    areaSqft: bigint;
    category: _DesignCategory;
    constructionSteps: Array<_ConstructionStep>;
    previewImageUrl: string;
}): {
    id: bigint;
    bhk?: bigint;
    floorPlanImageUrl: string;
    title: string;
    createdAt: Timestamp;
    tags: Array<string>;
    tier: DesignTier;
    description: string;
    materials: Array<Material>;
    estimatedCostMax: bigint;
    estimatedCostMin: bigint;
    areaSqft: bigint;
    category: DesignCategory;
    constructionSteps: Array<ConstructionStep>;
    previewImageUrl: string;
} {
    return {
        id: value.id,
        bhk: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.bhk)),
        floorPlanImageUrl: value.floorPlanImageUrl,
        title: value.title,
        createdAt: value.createdAt,
        tags: value.tags,
        tier: from_candid_DesignTier_n22(_uploadFile, _downloadFile, value.tier),
        description: value.description,
        materials: value.materials,
        estimatedCostMax: value.estimatedCostMax,
        estimatedCostMin: value.estimatedCostMin,
        areaSqft: value.areaSqft,
        category: from_candid_DesignCategory_n24(_uploadFile, _downloadFile, value.category),
        constructionSteps: from_candid_vec_n26(_uploadFile, _downloadFile, value.constructionSteps),
        previewImageUrl: value.previewImageUrl
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationDays: bigint;
    step: bigint;
    activities: [] | [string];
    description: string;
    stageImageUrl: [] | [string];
    stageName: [] | [string];
    stageType: [] | [string];
}): {
    durationDays: bigint;
    step: bigint;
    activities?: string;
    description: string;
    stageImageUrl?: string;
    stageName?: string;
    stageType?: string;
} {
    return {
        durationDays: value.durationDays,
        step: value.step,
        activities: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.activities)),
        description: value.description,
        stageImageUrl: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.stageImageUrl)),
        stageName: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.stageName)),
        stageType: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.stageType))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InquiryStatus;
    projectType: string;
    submitterPrincipal: [] | [Principal];
    name: string;
    createdAt: _Timestamp;
    description: string;
    email: string;
    phone: string;
    budgetMax: bigint;
    budgetMin: bigint;
}): {
    id: bigint;
    status: InquiryStatus;
    projectType: string;
    submitterPrincipal?: Principal;
    name: string;
    createdAt: Timestamp;
    description: string;
    email: string;
    phone: string;
    budgetMax: bigint;
    budgetMin: bigint;
} {
    return {
        id: value.id,
        status: from_candid_InquiryStatus_n4(_uploadFile, _downloadFile, value.status),
        projectType: value.projectType,
        submitterPrincipal: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.submitterPrincipal)),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        email: value.email,
        phone: value.phone,
        budgetMax: value.budgetMax,
        budgetMin: value.budgetMin
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    displayName: string;
    createdAt: _Timestamp;
    tier: _UserTier;
    email: string;
    savedDesignIds: Array<bigint>;
}): {
    principal: Principal;
    displayName: string;
    createdAt: Timestamp;
    tier: UserTier;
    email: string;
    savedDesignIds: Array<bigint>;
} {
    return {
        principal: value.principal,
        displayName: value.displayName,
        createdAt: value.createdAt,
        tier: from_candid_UserTier_n33(_uploadFile, _downloadFile, value.tier),
        email: value.email,
        savedDesignIds: value.savedDesignIds
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bhk: [] | [bigint];
    title: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    tier: _DesignTier;
    estimatedCostMax: bigint;
    estimatedCostMin: bigint;
    areaSqft: bigint;
    category: _DesignCategory;
    previewImageUrl: string;
}): {
    id: bigint;
    bhk?: bigint;
    title: string;
    createdAt: Timestamp;
    tags: Array<string>;
    tier: DesignTier;
    estimatedCostMax: bigint;
    estimatedCostMin: bigint;
    areaSqft: bigint;
    category: DesignCategory;
    previewImageUrl: string;
} {
    return {
        id: value.id,
        bhk: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.bhk)),
        title: value.title,
        createdAt: value.createdAt,
        tags: value.tags,
        tier: from_candid_DesignTier_n22(_uploadFile, _downloadFile, value.tier),
        estimatedCostMax: value.estimatedCostMax,
        estimatedCostMin: value.estimatedCostMin,
        areaSqft: value.areaSqft,
        category: from_candid_DesignCategory_n24(_uploadFile, _downloadFile, value.category),
        previewImageUrl: value.previewImageUrl
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ultraPremium: null;
} | {
    premium: null;
} | {
    free: null;
}): DesignTier {
    return "ultraPremium" in value ? DesignTier.ultraPremium : "premium" in value ? DesignTier.premium : "free" in value ? DesignTier.free : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: null;
} | {
    residential: null;
} | {
    apartments: null;
} | {
    smallBusiness: null;
} | {
    dairyFarms: null;
}): DesignCategory {
    return "custom" in value ? DesignCategory.custom : "residential" in value ? DesignCategory.residential : "apartments" in value ? DesignCategory.apartments : "smallBusiness" in value ? DesignCategory.smallBusiness : "dairyFarms" in value ? DesignCategory.dairyFarms : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notAuthenticated: null;
} | {
    notFound: null;
}): Variant_ok_notAuthenticated_notFound {
    return "ok" in value ? Variant_ok_notAuthenticated_notFound.ok : "notAuthenticated" in value ? Variant_ok_notAuthenticated_notFound.notAuthenticated : "notFound" in value ? Variant_ok_notAuthenticated_notFound.notFound : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notAuthenticated: null;
} | {
    notFound: null;
} | {
    limitReached: null;
}): Variant_ok_notAuthenticated_notFound_limitReached {
    return "ok" in value ? Variant_ok_notAuthenticated_notFound_limitReached.ok : "notAuthenticated" in value ? Variant_ok_notAuthenticated_notFound_limitReached.notAuthenticated : "notFound" in value ? Variant_ok_notAuthenticated_notFound_limitReached.notFound : "limitReached" in value ? Variant_ok_notAuthenticated_notFound_limitReached.limitReached : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfilePublic;
} | {
    notAuthenticated: null;
}): {
    __kind__: "ok";
    ok: UserProfilePublic;
} | {
    __kind__: "notAuthenticated";
    notAuthenticated: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfilePublic_n31(_uploadFile, _downloadFile, value.ok)
    } : "notAuthenticated" in value ? {
        __kind__: "notAuthenticated",
        notAuthenticated: value.notAuthenticated
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    responded: null;
} | {
    pending: null;
} | {
    reviewed: null;
}): InquiryStatus {
    return "responded" in value ? InquiryStatus.responded : "pending" in value ? InquiryStatus.pending : "reviewed" in value ? InquiryStatus.reviewed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notAuthorized: null;
} | {
    notFound: null;
}): Variant_ok_notAuthorized_notFound {
    return "ok" in value ? Variant_ok_notAuthorized_notFound.ok : "notAuthorized" in value ? Variant_ok_notAuthorized_notFound.notAuthorized : "notFound" in value ? Variant_ok_notAuthorized_notFound.notFound : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InquiryPublic>): Array<InquiryPublic> {
    return value.map((x)=>from_candid_InquiryPublic_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConstructionStep>): Array<ConstructionStep> {
    return value.map((x)=>from_candid_ConstructionStep_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Design>): Array<Design> {
    return value.map((x)=>from_candid_Design_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DesignSummary>): Array<DesignSummary> {
    return value.map((x)=>from_candid_DesignSummary_n41(_uploadFile, _downloadFile, x));
}
function to_candid_CostCalculatorInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CostCalculatorInput): _CostCalculatorInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_DesignCategory_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignCategory): _DesignCategory {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_DesignFilter_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignFilter): _DesignFilter {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_DesignTier_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignTier): _DesignTier {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): _InquiryStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MaterialGrade_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialGrade): _MaterialGrade {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Region_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): _Region {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserTier_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserTier): _UserTier {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: Region;
    materialGrade: MaterialGrade;
    areaSqft: bigint;
}): {
    region: _Region;
    materialGrade: _MaterialGrade;
    areaSqft: bigint;
} {
    return {
        region: to_candid_Region_n14(_uploadFile, _downloadFile, value.region),
        materialGrade: to_candid_MaterialGrade_n16(_uploadFile, _downloadFile, value.materialGrade),
        areaSqft: value.areaSqft
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tier?: DesignTier;
    category?: DesignCategory;
}): {
    tier: [] | [_DesignTier];
    category: [] | [_DesignCategory];
} {
    return {
        tier: value.tier ? candid_some(to_candid_DesignTier_n37(_uploadFile, _downloadFile, value.tier)) : candid_none(),
        category: value.category ? candid_some(to_candid_DesignCategory_n38(_uploadFile, _downloadFile, value.category)) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): {
    responded: null;
} | {
    pending: null;
} | {
    reviewed: null;
} {
    return value == InquiryStatus.responded ? {
        responded: null
    } : value == InquiryStatus.pending ? {
        pending: null
    } : value == InquiryStatus.reviewed ? {
        reviewed: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): {
    semiUrban: null;
} | {
    urban: null;
} | {
    rural: null;
} {
    return value == Region.semiUrban ? {
        semiUrban: null
    } : value == Region.urban ? {
        urban: null
    } : value == Region.rural ? {
        rural: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialGrade): {
    premium: null;
} | {
    basic: null;
} | {
    standard: null;
} {
    return value == MaterialGrade.premium ? {
        premium: null
    } : value == MaterialGrade.basic ? {
        basic: null
    } : value == MaterialGrade.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignCategory): {
    custom: null;
} | {
    residential: null;
} | {
    apartments: null;
} | {
    smallBusiness: null;
} | {
    dairyFarms: null;
} {
    return value == DesignCategory.custom ? {
        custom: null
    } : value == DesignCategory.residential ? {
        residential: null
    } : value == DesignCategory.apartments ? {
        apartments: null
    } : value == DesignCategory.smallBusiness ? {
        smallBusiness: null
    } : value == DesignCategory.dairyFarms ? {
        dairyFarms: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignTier): {
    ultraPremium: null;
} | {
    premium: null;
} | {
    free: null;
} {
    return value == DesignTier.ultraPremium ? {
        ultraPremium: null
    } : value == DesignTier.premium ? {
        premium: null
    } : value == DesignTier.free ? {
        free: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
